name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Branche utilisée pour le déploiement (modifiez si nécessaire)

permissions:
  id-token: write  # Ajoutez cette ligne pour donner les bonnes permissions au token

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

